### ISSUE TITLE
The game lacks an app icon.

### ISSUE THREAD

**Issue by Belgerum** [nternamehere/break-the-rematch#12]
We should probably get one before we publish. Renpy's default icon isn't great, and makes us look lazy.

**Comment by Belgerum** [comment]
![image](https://user-images.githubusercontent.com/6981764/50567082-da9df900-0d0e-11e9-8070-58c2844baee0.png)

**Comment by nternamehere** [comment]
Using one of the sprite heads temporarily till that gets sent my way. zzz

**Comment by nternamehere** [comment]
Updated to the shield.
