### ISSUE TITLE
Text sometimes intersects with buttons on the bottom of screen.

### ISSUE THREAD

**Issue by Belgerum** [nternamehere/break-the-rematch#13]
![image](https://user-images.githubusercontent.com/6981764/50566377-07e6a900-0d07-11e9-881f-0657db5de30a.png)

**Comment by Belgerum** [comment]
Personally, I think lines that are this long should probably get split into two separate lines anyway.

**Comment by nternamehere** [comment]
separating is definitely the way to go. Moving forward I'll separate all lines that are way to long for their own good.
