### ISSUE TITLE
Game creates 10 autosave files on system when only 6 slots are available in-game

### ISSUE THREAD

**Issue by Belgerum** [nternamehere/break-the-rematch#15]
There are only 6 slots per page in this GUI, and thus, the player can only utilize 6 autosave and 6 quicksave files. However, the game saves use Renpy's default value of 10 maximum instead of 6. This means that there can be up to 4 extra autosaves and 4 extra quicksaves stored that are not usable, and just take up unnecessary space.

This can be fixed by adding these two lines to the game. I suggest putting them in options.rpy.

```
define config.autosave_slots = 6
define config.quicksave_slots = 6
```

**Comment by nternamehere** [comment]
updated
