### ISSUE TITLE
Gym Background Rework

### ISSUE THREAD

**Issue by Belgerum** [nternamehere/break-the-rematch#21]
To save on filespace, I suggest replacing the "bg gym balls" background image with the following, and using layeredimage code to make it easily added to the empty version of the background, instead of including both full versions. I suggested some code through Discord earlier.

![bg_gym_just_balls](https://user-images.githubusercontent.com/6981764/51080610-1a6cc500-16ad-11e9-99b6-cc91f71edd97.png)

**Comment by nternamehere** [comment]
Updated the Gym files to deal with that.
